const imgDirectories:{fruits:string[],sports:string[],flags:string[],animals:string[],food:string[]} = {
    fruits: [
        "/matching-game-images/fruits/apple.png",
        "/matching-game-images/fruits/apple2.png",
        "/matching-game-images/fruits/apricot.png",
        "/matching-game-images/fruits/avocado.png",
        "/matching-game-images/fruits/blackberry.png",
        "/matching-game-images/fruits/blueberry.png",
        "/matching-game-images/fruits/broccoli.png",
        "/matching-game-images/fruits/carrot.png",
        "/matching-game-images/fruits/cherries.png",
        "/matching-game-images/fruits/corn.png",
        "/matching-game-images/fruits/cucumber.png",
        "/matching-game-images/fruits/eggplant.png",
        "/matching-game-images/fruits/fig.png",
        "/matching-game-images/fruits/grapes.png",
        "/matching-game-images/fruits/kiwi.png",
        "/matching-game-images/fruits/lemon.png",
        "/matching-game-images/fruits/mangosteen.png",
        "/matching-game-images/fruits/melon.png",
        "/matching-game-images/fruits/orange.png",
        "/matching-game-images/fruits/orange2.png",
        "/matching-game-images/fruits/papaya.png",
        "/matching-game-images/fruits/passion-fruit.png",
        "/matching-game-images/fruits/pea.png",
        "/matching-game-images/fruits/peach.png",
        "/matching-game-images/fruits/pear.png",
        "/matching-game-images/fruits/persimmon.png",
        "/matching-game-images/fruits/plum.png",
        "/matching-game-images/fruits/pomegranate.png",
        "/matching-game-images/fruits/raspberries.png",
        "/matching-game-images/fruits/salad.png",
        "/matching-game-images/fruits/star-fruit.png",
        "/matching-game-images/fruits/strawberry.png",
        "/matching-game-images/fruits/texas-red-grapefruit.png",
        "/matching-game-images/fruits/tomato.png",
        "/matching-game-images/fruits/watermelon.png",
    ],
    sports:[
        "/matching-game-images/sports/american-football.png",
        "/matching-game-images/sports/american-football-player.png",
        "/matching-game-images/sports/ball.png",
        "/matching-game-images/sports/baseball.png",
        "/matching-game-images/sports/basketball.png",
        "/matching-game-images/sports/basketball2.png",
        "/matching-game-images/sports/basketball-jersey.png",
        "/matching-game-images/sports/basketball-player.png",
        "/matching-game-images/sports/block.png",
        "/matching-game-images/sports/bowling.png",
        "/matching-game-images/sports/dumbbell.png",
        "/matching-game-images/sports/floorball.png",
        "/matching-game-images/sports/football.png",
        "/matching-game-images/sports/football-field.png",
        "/matching-game-images/sports/football-jersey.png",
        "/matching-game-images/sports/golf.png",
        "/matching-game-images/sports/jersey.png",
        "/matching-game-images/sports/pool.png",
        "/matching-game-images/sports/runningman.png",
        "/matching-game-images/sports/shoes.png",
        "/matching-game-images/sports/shoot.png",
        "/matching-game-images/sports/skiing.png",
        "/matching-game-images/sports/soccer-jersey.png",
        "/matching-game-images/sports/sports.png",
        "/matching-game-images/sports/swimming.png",
        "/matching-game-images/sports/tennis-ball.png",
        "/matching-game-images/sports/tennis-racket.png",
        "/matching-game-images/sports/volleyball.png",
        "/matching-game-images/sports/water-volleyball.png",
        "/matching-game-images/sports/weight-lifting.png",

    ],
    flags:[
        "/matching-game-images/flags/turkey.png",
        "/matching-game-images/flags/argentina.png",
        "/matching-game-images/flags/azerbaijan.png",
        "/matching-game-images/flags/belgium.png",
        "/matching-game-images/flags/brazil.png",
        "/matching-game-images/flags/cameroon.png",
        "/matching-game-images/flags/canada.png",
        "/matching-game-images/flags/croatia.png",
        "/matching-game-images/flags/denmark.png",
        "/matching-game-images/flags/german.png",
        "/matching-game-images/flags/greece.png",
        "/matching-game-images/flags/italy.png",
        "/matching-game-images/flags/japan.png",
        "/matching-game-images/flags/mexico.png",
        "/matching-game-images/flags/netherlands.png",
        "/matching-game-images/flags/norway.png",
        "/matching-game-images/flags/philippines.png",
        "/matching-game-images/flags/portugal.png",
        "/matching-game-images/flags/russia.png",
        "/matching-game-images/flags/singapore.png",
        "/matching-game-images/flags/slovakia.png",
        "/matching-game-images/flags/southkorea.png",
        "/matching-game-images/flags/southafrica.png",
        "/matching-game-images/flags/sweden.png",
        "/matching-game-images/flags/switzerland.png",
        "/matching-game-images/flags/thailand.png",
        "/matching-game-images/flags/usa.png",
    ],
    animals:[
        "/matching-game-images/animals/bear.png",
        "/matching-game-images/animals/bee.png",
        "/matching-game-images/animals/bird.png",
        "/matching-game-images/animals/bird1.png",
        "/matching-game-images/animals/bull.png",
        "/matching-game-images/animals/butterfly.png",
        "/matching-game-images/animals/cat.png",
        "/matching-game-images/animals/chameleon.png",
        "/matching-game-images/animals/chick.png",
        "/matching-game-images/animals/clown-fish.png",
        "/matching-game-images/animals/crab.png",
        "/matching-game-images/animals/dog.png",
        "/matching-game-images/animals/dolphin.png",
        "/matching-game-images/animals/eagle.png",
        "/matching-game-images/animals/elephant.png",
        "/matching-game-images/animals/fox.png",
        "/matching-game-images/animals/frog.png",
        "/matching-game-images/animals/giraffe.png",
        "/matching-game-images/animals/goldfish.png",
        "/matching-game-images/animals/gorilla.png",
        "/matching-game-images/animals/hen.png",
        "/matching-game-images/animals/kiwi.png",
        "/matching-game-images/animals/koala.png",
        "/matching-game-images/animals/ladybug.png",
        "/matching-game-images/animals/lion.png",
        "/matching-game-images/animals/monkey.png",
        "/matching-game-images/animals/mouse.png",
        "/matching-game-images/animals/owl.png",
        "/matching-game-images/animals/panda.png",
        "/matching-game-images/animals/parrot.png",
        "/matching-game-images/animals/penguin.png",
        "/matching-game-images/animals/polarbear.png",
        "/matching-game-images/animals/rabbit.png",
        "/matching-game-images/animals/sealion.png",
        "/matching-game-images/animals/shark.png",
        "/matching-game-images/animals/snail.png",
        "/matching-game-images/animals/squirrel.png",
        "/matching-game-images/animals/tiger.png",
        "/matching-game-images/animals/turtle.png",
        "/matching-game-images/animals/whale.png",
        "/matching-game-images/animals/zebra.png",
    ],
    food:[
        "/matching-game-images/food/bacon.png",
        "/matching-game-images/food/baklava.png",
        "/matching-game-images/food/beer.png",
        "/matching-game-images/food/bread.png",
        "/matching-game-images/food/burrito.png",
        "/matching-game-images/food/cake.png",
        "/matching-game-images/food/cakeslice.png",
        "/matching-game-images/food/cheese.png",
        "/matching-game-images/food/cheesecake.png",
        "/matching-game-images/food/chickenleg.png",
        "/matching-game-images/food/cocktail.png",
        "/matching-game-images/food/coconutdrink.png",
        "/matching-game-images/food/coffeecup.png",
        "/matching-game-images/food/cola.png",
        "/matching-game-images/food/cookies.png",
        "/matching-game-images/food/cupcake.png",
        "/matching-game-images/food/dango.png",
        "/matching-game-images/food/dessert.png",
        "/matching-game-images/food/dessert1.png",
        "/matching-game-images/food/donerkebab.png",
        "/matching-game-images/food/donut.png",
        "/matching-game-images/food/donut1.png",
        "/matching-game-images/food/egg.png",
        "/matching-game-images/food/fish.png",
        "/matching-game-images/food/friedpotatoes.png",
        "/matching-game-images/food/hamburger.png",
        "/matching-game-images/food/hotdog.png",
        "/matching-game-images/food/icecream.png",
        "/matching-game-images/food/icecream1.png",
        "/matching-game-images/food/icecreamstick.png",
        "/matching-game-images/food/juicebox.png",
        "/matching-game-images/food/kebab.png",
        "/matching-game-images/food/latte.png",
        "/matching-game-images/food/lemonade.png",
        "/matching-game-images/food/lobster.png",
        "/matching-game-images/food/milk.png",
        "/matching-game-images/food/orangejuice.png",
        "/matching-game-images/food/pancake.png",
        "/matching-game-images/food/pizza.png",
        "/matching-game-images/food/poinsettia.png",
        "/matching-game-images/food/popcorn.png",
        "/matching-game-images/food/popsicle.png",
        "/matching-game-images/food/ramen.png",
        "/matching-game-images/food/rice.png",
        "/matching-game-images/food/rollcake.png",
        "/matching-game-images/food/salad.png",
        "/matching-game-images/food/smoothie.png",
        "/matching-game-images/food/soda.png",
        "/matching-game-images/food/soup.png",
        "/matching-game-images/food/spaghetti.png",
        "/matching-game-images/food/sundae.png",
        "/matching-game-images/food/sushi.png",
        "/matching-game-images/food/taco.png",
        "/matching-game-images/food/tiramisu.png",
        "/matching-game-images/food/water.png",
    ]
};

const shuffleArray = (myfirstArray:{fruits:string[],flags:string[],animals:string[],sports:string[],food:string[]},imagetypes:string,neededImagesNumber:number) : string[]=>{
    var myArray = myfirstArray.fruits;
    if(imagetypes == "sports"){
         myArray = myfirstArray.sports;
    }
    else if(imagetypes == "flags"){
         myArray = myfirstArray.flags;
    }
    else if(imagetypes == "animals"){
         myArray = myfirstArray.animals;
    }   
    else if(imagetypes == "food"){
        myArray = myfirstArray.food;
   }
    for(let i=myArray.length-1;i>0;i--){
        const j = Math.floor(Math.random() * (i+1));
        [myArray[i],myArray[j]] = [myArray[j],myArray[i]];
    }
    const firstShuffle = [...myArray.slice(0,neededImagesNumber),...myArray.slice(0,neededImagesNumber)];
    for(let i=firstShuffle.length-1;i>0;i--){
        const j = Math.floor(Math.random() * (i+1));
        [firstShuffle[i],firstShuffle[j]] = [firstShuffle[j],firstShuffle[i]];
    }   
    return firstShuffle;
}

export {shuffleArray,imgDirectories};